# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(724, 655)
        Main.setStyleSheet("QWidget#painel_principal{\n"
                           "    background-color: #14213d\n"
                           "}\n"
                           "\n"
                           "QWidget#componentes > QLabel{\n"
                           "    font-size: 15px;\n"
                           "    color: #fca311\n"
                           "}\n"
                           "\n"
                           "QWidget#componentes > QLineEdit, QComboBox{\n"
                           "    font-size: 15px;\n"
                           "    background-color: #fca311;\n"
                           "    color: #14213d;\n"
                           "    padding: 10px\n"
                           "}\n"
                           "\n"
                           "QWidget#botoes > QPushButton{\n"
                           "    font-size: 15px;\n"
                           "    background-color: #fca311;\n"
                           "    color: #14213d;\n"
                           "    padding: 10px;\n"
                           "}\n"
                           "\n"
                           "QWidget#titulo > QLabel{\n"
                           "    font-size: 25px;\n"
                           "    background-color: #fca311;\n"
                           "    color: #14213d;\n"
                           "}\n"
                           "\n"
                           "")
        self.painel_principal = QtWidgets.QWidget(Main)
        self.painel_principal.setObjectName("painel_principal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.painel_principal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo = QtWidgets.QWidget(self.painel_principal)
        self.titulo.setMinimumSize(QtCore.QSize(0, 70))
        self.titulo.setMaximumSize(QtCore.QSize(16777214, 70))
        self.titulo.setObjectName("titulo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.titulo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_titulo = QtWidgets.QLabel(self.titulo)
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.verticalLayout_3.addWidget(self.lbl_titulo)
        self.verticalLayout_2.addWidget(self.titulo)
        self.componentes = QtWidgets.QWidget(self.painel_principal)
        self.componentes.setObjectName("componentes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.componentes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_mensagem = QtWidgets.QLabel(self.componentes)
        self.lbl_mensagem.setStyleSheet("color: green;")
        self.lbl_mensagem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mensagem.setObjectName("lbl_mensagem")
        self.verticalLayout.addWidget(self.lbl_mensagem)
        self.lbl_nome = QtWidgets.QLabel(self.componentes)
        self.lbl_nome.setObjectName("lbl_nome")
        self.verticalLayout.addWidget(self.lbl_nome)
        self.edt_nome = QtWidgets.QLineEdit(self.componentes)
        self.edt_nome.setMinimumSize(QtCore.QSize(0, 40))
        self.edt_nome.setMaximumSize(QtCore.QSize(16777215, 40))
        self.edt_nome.setObjectName("edt_nome")
        self.verticalLayout.addWidget(self.edt_nome)
        self.lbl_sexo = QtWidgets.QLabel(self.componentes)
        self.lbl_sexo.setObjectName("lbl_sexo")
        self.verticalLayout.addWidget(self.lbl_sexo)
        self.cmb_sexo = QtWidgets.QComboBox(self.componentes)
        self.cmb_sexo.setObjectName("cmb_sexo")
        self.cmb_sexo.addItem("")
        self.cmb_sexo.addItem("")
        self.verticalLayout.addWidget(self.cmb_sexo)
        self.lbl_salario = QtWidgets.QLabel(self.componentes)
        self.lbl_salario.setObjectName("lbl_salario")
        self.verticalLayout.addWidget(self.lbl_salario)
        self.edt_salario = QtWidgets.QLineEdit(self.componentes)
        self.edt_salario.setMinimumSize(QtCore.QSize(0, 40))
        self.edt_salario.setMaximumSize(QtCore.QSize(16777215, 40))
        self.edt_salario.setObjectName("edt_salario")
        self.verticalLayout.addWidget(self.edt_salario)
        self.lbl_departamento = QtWidgets.QLabel(self.componentes)
        self.lbl_departamento.setObjectName("lbl_departamento")
        self.verticalLayout.addWidget(self.lbl_departamento)
        self.edt_departamento = QtWidgets.QLineEdit(self.componentes)
        self.edt_departamento.setMinimumSize(QtCore.QSize(0, 40))
        self.edt_departamento.setMaximumSize(QtCore.QSize(16777215, 40))
        self.edt_departamento.setObjectName("edt_departamento")
        self.verticalLayout.addWidget(self.edt_departamento)
        self.verticalLayout_2.addWidget(self.componentes)
        self.botoes = QtWidgets.QWidget(self.painel_principal)
        self.botoes.setObjectName("botoes")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.botoes)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_salvar = QtWidgets.QPushButton(self.botoes)
        self.btn_salvar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_salvar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_salvar.setObjectName("btn_salvar")
        self.horizontalLayout.addWidget(self.btn_salvar)
        self.btn_fechar = QtWidgets.QPushButton(self.botoes)
        self.btn_fechar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_fechar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_fechar.setObjectName("btn_fechar")
        self.horizontalLayout.addWidget(self.btn_fechar)
        self.verticalLayout_2.addWidget(self.botoes)
        self.tbl_funcionarios = QtWidgets.QTableWidget(self.painel_principal)
        self.tbl_funcionarios.setObjectName("tbl_funcionarios")
        self.tbl_funcionarios.setColumnCount(4)
        self.tbl_funcionarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_funcionarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_funcionarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_funcionarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_funcionarios.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tbl_funcionarios)
        Main.setCentralWidget(self.painel_principal)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.lbl_titulo.setText(_translate("Main", "LISTAGEM E CADASTRO DE FUNCIONANÁRIOS"))
        self.lbl_mensagem.setText(_translate("Main", "TextLabel"))
        self.lbl_nome.setText(_translate("Main", "Nome"))
        self.lbl_sexo.setText(_translate("Main", "Sexo"))
        self.cmb_sexo.setItemText(0, _translate("Main", "Masculino"))
        self.cmb_sexo.setItemText(1, _translate("Main", "Feminino"))
        self.lbl_salario.setText(_translate("Main", "Salário"))
        self.lbl_departamento.setText(_translate("Main", "Departamento"))
        self.btn_salvar.setText(_translate("Main", "Salvar"))
        self.btn_fechar.setText(_translate("Main", "Fechar"))
        item = self.tbl_funcionarios.horizontalHeaderItem(0)
        item.setText(_translate("Main", "Nome"))
        item = self.tbl_funcionarios.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Sexo"))
        item = self.tbl_funcionarios.horizontalHeaderItem(2)
        item.setText(_translate("Main", "Salário"))
        item = self.tbl_funcionarios.horizontalHeaderItem(3)
        item.setText(_translate("Main", "Departamento"))
